version: "3.7"
services:
    # nginx:
    #     image: nginx:stable-alpine
    #     container_name: nginx-laravel
    #     ports:
    #         - 7777:80
    #     volumes:
    #         #- ./src:/var/www/html
    #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - php
    #         - mysql
    #     networks:
    #         - laravel-network
    
    mysql:
        image: mysql:5.7
        container_name: mysql-laravel
        restart: always
        environment:
            MYSQL_DATABSE: laravel
            MSYQL_USER: laravel
            MYSQL_PASSWORD: my-secret
            MYSQL_ROOT_PASSWORD: my-srecret-root
        ports:
            - 13306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            dev-network:
                aliases:
                    - mysqlhost

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-for-laravel
        volumes:
            - ./src:/var/www/html
        ports:
            - 9001:80
            - 8080:8080
        networks:
            dev-network:
                aliases:
                    - phphost

networks:
    dev-network: